# http server
core-http-server:
	node src/core_http/server.js 

# please have core-http-server running before running this goal
core-url: 
	node src/core_http/url.js

# please have core-http-server running before running this goal
core-http-request-low-level:
	node src/core_http/low_level_request.js


# file system
core-fs:
	node src/core_fs/async_file_read.js
	node src/core_fs/sync_file_read.js

# os
core-os:
	node src/core_os/os_info.js