# http server
core-http-server:
	node core_http/server.js

# please have core-tcp-server.js running before running this goal
core-curl: 
	node core_curl/curl.js

# file system
core-fs:
	node core_fs/async_file_read.js
	node core_fs/sync_file_read.js

# os
core-os:
	node core_os/os_info.js